### ISSUE TITLE
I can see nothing

### ISSUE THREAD

**Issue by xbfrnd** [Capsize-Games/airunner#248] opened 2023-06-17 07:59 UTC
After generating, there is no image.

**Comment by xbfrnd** [comment] 2023-06-28 02:17
I tried on v1.15 and 1.17.
I work on Windows, GTX 1660 6Gb
I use the itch.io version which I download on itch.io as a Zip file.
Model: Diff v1, blueberrymix/20step with NSFW Off
And yes i see the black image.
Please help me to resolve this issue.

Vào Th 7, 24 thg 6, 2023 vào lúc 00:09 w4ffl35 ***@***.***>
đã viết:

**Comment by w4ffl35** [comment] 2023-06-28 14:21
Ok thanks - a few more questions to help me determine what the cause of your issue is:

- Do you see any error messages in the console when you generate the image? 
- Are you using any LoRA files?
- Are you using an textual inversion (embedding) files?
- What are your memory settings set to?

In order to get help faster, feel free to join our discord server (you can find a link in the help menu of the app).
In the meantime I will attempt to recreate the issue.

**Comment by xbfrnd** [comment] 2023-06-29 07:38
No error when generating, i've just got an error message when opening up
like the image below.
I don't use any LORA or embedding.
My setting is like the image.
[image: image.png][image: image.png]

Vào Th 4, 28 thg 6, 2023 vào lúc 21:21 w4ffl35 ***@***.***>
đã viết:

**Comment by w4ffl35** [comment] 2023-06-29 08:59
I'm sorry but the image you're posting isn't displaying. You may have better results in resolving this issue if you join our discord server. Additionally please try updating to v1.18.1 which was released several hours ago as it may fix your bug. 

If the app is crashing before it even runs, you will see an error as long as you run it via the command line. 

We respond very quickly and resolve any issues such as these in discord. 
You can get to our discord server here: 
https://discord.gg/PUVDDCJ7gz

**Closed** 2023-06-29 09:02 UTC
